#!/usr/bin/env bash

mkcd() {
	mkdir -p "$1" && cd "$1"
}

file_exists() {
	# variables inside functions have global scope - Buggrisk
	# "local" makes variables local to this function
	local file="$1"
#	if [[ -f "$file" ]]; then
#		return 0
#	else
#		return 1
#	fi



file_exists "$1"
echo "$file"

[[ -f "$file" ]] || return 1
}

bak() {
	local file="$1"
	file_exists "$file"

	local backup="$file.bak.$(date +%y%m%d_%H%M%S)"
	cp "$file" "$backup"

}
